language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run gulp travis --COMMIT=$TRAVIS_COMMIT --GITHUB_TOKEN=$GITHUB_TOKEN
env:
  - secure: "L+t6TT1dCcnRk9xF6tIcmBBcQfiNElbZaJ8fffRAP2PoZh/1zzbD391A5WM1hQ3a3AZm38w/9UdAhxgd/0GN7GZdhaRA5z6EY9HZ3nUtnILVoKQpq/zE3WGct6nBcNW3HX7wT5eCWS/bDG+bUD4AbdZOj4+vVbLkRDt8BCqtV6I6MTBWIxmG2b5cDDrsLl1NYb270ojjNBcD9DPefGWe2uHAxKYBJiC6kgS5aebcmVjqVWahxWhMIBXrkNbyPzHlPuWjkNsq68WL+XLd77Xd7q6Zah84kpxSAKVYxo0cZK+shh9UzduLtqac0ENc+JEh5leps9jBnkypXPIWHwECL/Gu8AT12xlr2u4KEWQIZ5opc7JxO7U2OUIs+VfJvF3qPojArq6HwtqOhJ1eSb45/hzh4N0znWjOf+UrdvtUDNQNEdymyw3ws0g/d0T0ciKTi1mK1kOuBzfmyjYWAJivB2jW5y/NyCzJi8Xu782rNj4alDpQSAYINhRW3yiPPq+f3jh/+VoHPRp2/cxQujSJHvIMwkZN/DCDnLzq0XuKZccz1bgYcT9cQBnoXVQ1sxEibnoOL5IwURLyiT9NLXrPV0II7uvhgQSASAS4BR5K7hPX+tum2rY3WIkzciFDAVqY32LTbJNKZF8VUChO0r7enmDGRhSwwQQsNYSITrH4BKU="
